### ISSUE TITLE
Table / Model Assertions

### ISSUE THREAD

**Issue by aidan-casey** [Astrotomic/phpunit-assertions#1]
Would you accept a pull request for some further assertions around Laravel tables and models? See below for a couple specifics that come to mind.

Tables:

* `assertTableExists`
* `assertTableHasSchema` - Accepts an array and asserts the columns in that array match the columns a table has.
* `assertTableHasColumn`

Model relationships such as:

* `assertBelongsTo`
* `assertHasMany`
* etc.

**Comment by Gummibeer** [comment]
Hey,

the model assertions sound interesting. Should they check that the model has a relationship of a given type? Or should they check that a model is part of another model's relationship?

At all, could you provide examples of how you would call them - so the method signature?

Regarding the table assertions: do you test your apps migrations? 😱 Or is it to test logic like multi-database tenancy?
I'm not really sure why/how/when you would use them? As it's like testing that a config key exists - I assume that your app would crash if not!?^^
Or do you have projects dynamically generating new tables/columns on runtime? 😱

**Comment by aidan-casey** [comment]
I was originally gonna say I would foresee it handling both (asserts the relationship method returns the correct type and checks that the model exists) but it's probably better to separate those.

So a revised example:

* `assertHasBelongsTo` - Asserts model has the specified relationship and it returns the BelongsTo relation class.
* `assertBelongsTo` - Asserts the originator model belongs to the parent model.

Now I'm struggling on the names though, not sure if it's clear enough what the difference is.

Heh, you have a right to be skeptical of that one. We don't do it for every app, but for rather large ones with lots of migrations, we put a basic schema check as the first thing in all our models. No type checking or anything, just ensures the passed array of columns are the only ones that exist. It also helps to document the schematic a little as model attributes are pretty dynamic.

That said, I get there might not be a widespread use case for that one. It can be overkill.

**Comment by Gummibeer** [comment]
Okay, so my 2 cents.
I think that one assertion to test for relationship would be enough.

Testing the type and existence of relationship isn't hard as it's `assertInstanceOf(BelongsTo::class, $model->relation())`.
For me there isn't enough need to add this as a macro as it would end in a lot of assertions. And would possibly end up in more requests for "assert method existence and return type" as that's what this check would do.

Having one assertion per relationship type would mean that there's any difference between them regarding the check. But independent if we would do it `whereKey()->exists()` or `whereKey()->first()->is($related)` it's not important which type of relationship it is.
In turn it would be much harder for all with dedicated methods as you have to think which type it is and which direction as some change type from the other side.

**Comment by Gummibeer** [comment]
@aidan-casey what do you think about this assertion?
https://github.com/Astrotomic/phpunit-assertions/blob/de15e8ba4b47db349907ea5cdd770ebf9419d887/src/Laravel/ModelAssertions.php#L38-L46
Is it okay/enough? Is it what you had in mind?

**Comment by aidan-casey** [comment]
@Gummibeer - What I had originally been after was an assertion that a relationship existed, not necessarily that two specific models were related to each other. So very rough example:

```php
public static function assertRelated(Model $model, $actual, string $relation) 
{ 
    PHPUnit::assertInstanceOf(Model::class, $actual); 
    PHPUnit::assertTrue(method_exists($model, $relation)); 
    PHPUnit::assertInstanceOf(Relation::class, $model->$relation()); 

    $related = $model->$relation()->getRelated(); 
    PHPUnit::assertInstanceOf($actual::class, $related);
}
```

Main reason I was thinking of asserting it that way is because you will probably use the relationship on the actual model to create a related item, so it is somewhat pointless to then assert it as you have above.

That said, there's not necessarily anything bad about what you have there. It does look good. 🙂

**Comment by Gummibeer** [comment]
Okay.
I would keep the `assertRelated()` as-is. my use-case, as we use this logic already, is for example an API that receives a list of model and syncs them or attaches/detaches.
In this case I would want to test, after the request, that the new list of models is related.
In this scenario I will also add a `assertNotrelated()` which will test that these two models have no relation (anymore).

Your example is useful if you want to check that you've properly setup the relationships - so more a once in a lifetime.
As it's some more assertions needed I will still add this macro - how about `assertRelation()`? Which could also get (optional) the type of the relationship.
So something like
```php
abstract public static function assertRelated(
    Model $model, 
    Model|string $related, 
    string $relation, 
    string $type
): void;
```

**Comment by Gummibeer** [comment]
https://github.com/Astrotomic/phpunit-assertions/releases/tag/0.3.0
